#pragma once

#include "net_core.h"
#include "layer.h"
#include "activation.h"
#include "batchnormalization.h"
#include "convolution.h"
#include "costfunction.h"
#include "dropout.h"
#include "fullconnection.h"
#include "pool.h"
#include "prelu.h"
#include "reshape.h"
#include "softmax.h"

#include "nnapi.h"
#include "optimalize.h"
#include "traindata.h"
#include "train.h"
#include "net.h"
#include "../lzh.h"